### ISSUE TITLE
Filter feature 

### ISSUE THREAD

**Issue by Skarsnik** [tony-o/perl6-html-parser-xml#12]
I write a filter feature in https://github.com/Skarsnik/perl6-html-parser-xml

It work like in a similar fashion that XML::Element::elements method

eg :
`$parse.parse($html, :TAG<div>, :class<content>);
$parse.parse($html, :TAG<div>, :class<content>, :SINGLE);`

The idea was to reduce time parsing since modern website can offer lot of useless information (banner, add, menu, footer). It also reduce the size of the xml doc produced.
The SINGLE make the module stop after the concerned tag is closed.

The modif mainly focus on avoiding creating extra xml elements, maybe it can skip parsing all attributes if the tag is not in the search scope. (but I don't remember if html allow < or > in attribute value)

**Comment by tony-o** [comment]
Can you write this out further please?  Should it ignore all child elements?  Should it parse child elements but insert them above the filtered node in the hierarchy?  Perhaps some examples would help, I can’t seem to think of a logical way to make this work as desired.

On September 16, 2015 at 3:51:52 PM, Skarsnik (notifications@github.com<mailto:notifications@github.com>) wrote:

I write a filter feature in https://github.com/Skarsnik/perl6-html-parser-xml

It work like in a similar fashion that XML::Element::elements method

eg :
$parse.parse($html, :TAG

, :class);
$parse.parse($html, :TAG
, :class, :SINGLE);

The idea was to reduce time parsing since modern website can offer lot of useless information (banner, add, menu, footer). It also reduce the size of the xml doc produced.
The SINGLE make the module stop after the concerned tag is closed.

The modif mainly focus on avoiding creating extra xml elements, maybe it can skip parsing all attributes if the tag is not in the search scope. (but I don't remember if html allow < or > in attribute value)

**Comment by Skarsnik** [comment]
It keep the childs. You can resume the filter as to create a subtree of the whole document : 
check at https://github.com/Skarsnik/perl6-html-parser-xml/blob/master/t/09_filter.t ( and the associate https://github.com/Skarsnik/perl6-html-parser-xml/blob/master/t/data/fancy.html)

**Comment by tony-o** [comment]
I think these features are better reserved for something like XML::Query or some kind of xpath module.


On September 16, 2015 at 3:57:42 PM, Skarsnik (notifications@github.com<mailto:notifications@github.com>) wrote:

It keep the childs. You can resume the filter as to create a subtree of the whole document :
check at https://github.com/Skarsnik/perl6-html-parser-xml/blob/master/t/09_filter.t ( and the associate https://github.com/Skarsnik/perl6-html-parser-xml/blob/master/t/data/fancy.html)

**Comment by Skarsnik** [comment]
Well I wrote that because the module is very slow on something like a 200ko+ webpage and I did not need everything on the webpage. It speed up also every elements call I do just after by not having to search through useless garbage on the xml::doc the module produce

**Comment by tony-o** [comment]
If you write a clearer of example of that filtering would work along with some examples, I’ll write a module to do this, I think it belongs in a pre-processor or post-processor.

**Comment by Skarsnik** [comment]
I don't know if you had a look at what I did.
When I found a tag matching the filter, I save his depth (and set a var to say I am in it). The code creating the xml-node is ignored if we are not (in) the tag.


A good example is like a webpage with a banner (with maybe a menu), some sub menu on the left, the content in the middle, some ads at the end and a footer. That could create a xml doc with lots of elements. In most case you want only a part of the document (ie the content at the center).

so instead of maybe call `h:p:x.parse($html).elements(:TAG<div>, :class<content>);` wich parse everything from the document and create huge xml-tree you could call `h:p:x.parse($html, :TAG<div>, :class<content>, :SINGLE)` and get only the content 'div' in your xml-tree and it make the module stop, probably skipping parsing the footer at all.

A concrete example for me: I try to make stats about the stories I read on a fan-fiction website. I need to scrap the different page of my bookshelf (it only display 10 stories at a time and the website does not offer an api for bookshelf). each page are like 250ko with lot a div and tags, creating a quite huge xml-tree. But in the end I need maybe 5% of the page's content


Why put filtering in this module?

Perl6/Rakudo is slow (for now)
Another module (web::scrapper I think) use this module and perform xml::elements request to find stuff. the xml::element requests are not that slow comparing to the parse time.
Html::restrict do the same (wish is kind of make this module pointless IMO)

The module is already parsing the html. Filtering before could probably be a good idea, but the module already do most of the work.
